### ISSUE TITLE
Allow sites to specify PHP version

### ISSUE THREAD

**Issue by brandonkelly** [craftcms/nitro#105]
Each site should be able to specify their own PHP version via a `php` property under `sites` in the config, and Nitro should auto-install the required versions if they don’t exist.

```yaml
sites:
 - hostname: example.test
   webroot: /nitro/sites/example.test/web
   php: "7.2"
```
