### ISSUE TITLE
Getting `path` repositories to work for local development

### ISSUE THREAD

**Issue by bencroker** [craftcms/nitro#112]
During development, many plugin developers us use a [path repository](https://docs.craftcms.com/v3/extend/plugin-guide.html#path-repository), which symlinks the plugin into the `vendor` folder. 

After doing this, Nitro throws an error as it does not appear to mount the symlink. 
```
include(/nitro/sites/craft35.nitro/vendor/composer/../putyourlightson/craft-elements-panel/src/ElementsPanel.php): failed to open stream: No such file or directory
```

Any recommendations on how to get this or something similar to work?

**Comment by lukeholder** [comment]
Can you link your composer.json's path repo config for the package?

Interested how it is setup. e.g:

```json
    {
      "type": "path",
      "url": "~/Code/Repositories/commerce3",
      "options": {
        "symlink": true
      }
    },
```

Are you using a relative or absolute filepath for the URL?

**Comment by lukeholder** [comment]
Oh, and the reason I ask is I haven't got it working either.

**Comment by bencroker** [comment]
I have all my plugins in a folder next to my Craft projects, so I use this:
```
  "repositories": [
      {
          "type": "path",
          "url": "../plugins/*",
          "symlink": true
      }
```

Setting the `url` to an absolute path doesn't seem to make any difference either.

**Comment by olivierbon** [comment]
Not sure how you mounted the site itself but if you [create a new mount](https://github.com/craftcms/nitro#adding-mounts) 

```
mounts:
  - source: ~/path/to/plugins
    dest: /nitro/plugins
```

Then run `nitro apply`.

Next, in your `composer.json` set your `url` as:

```
"repositories": [
    {
      "type": "path",
      "url": "/nitro/plugins/*"
    }
  ]
```

With that in place, run `composer install` from inside nitro (`nitro ssh` then go to you project) it should work.

**Comment by nfourtythree** [comment]
Hi @bencroker 

The key here is to make sure the structure is replicated similarly in both instances, your host machine and in the VM.

I have basically the same setup as you have and here is how I have it setup.

I have a `dev` directory inside my home directory with my code in

- `craft3-commerce3` is my project/site
- `commerce` is the Commerce repository
- `cms` is the Craft CMS repository

So the `repositories` section in `composer.json` inside `craft3-commerce3` looks like the following:

```json
  "repositories": [
    {
      "type": "path",
      "url": "~/dev/cms",
      "options": {
        "symlink": true
      }
    },
    {
      "type": "path",
      "url": "~/dev/commerce",
      "options": {
        "symlink": true
      }
    }
  ]
```

Then my `nitro-dev.yaml` file has the following setup:

```yaml
php: "7.2"
mounts:
  - source: ~/dev/cms
    dest: /nitro/dev/cms
  - source: ~/dev/commerce
    dest: /nitro/dev/commerce
  - source: ~/dev/craft3-commerce3
    dest: /nitro/dev/craft3-commerce3
databases:
  - engine: mysql
    version: "5.7"
    port: "3306"
sites:
  - hostname: commerce.nitro.test
    webroot: /nitro/dev/craft3-commerce3/web
```

You can then `composer install` on your host machine as normal and the symlinks created will work as expected.

Hope this helps!

**Comment by bencroker** [comment]
Thanks @nfourtythree. I followed your suggestions and can confirm that the `plugins` folder is now mounted. I can also see that my plugin `craft-elements-panel` is correctly symlinked, as indicated by the red colour.

![Screenshot 2020-05-07 at 13 07 17](https://user-images.githubusercontent.com/57572400/81287802-b3261180-9063-11ea-8d95-e2cd7e4bca1d.png)

However, I am still getting the error when I visit the CP:
```
include(/nitro/sites/craft35.nitro/vendor/composer/../putyourlightson/craft-elements-panel/src/ElementsPanel.php): failed to open stream: No such file or directory
```

My `nitro-dev.yaml`:

```
php: "7.4"
mounts:
  - source: ~/sites/plugins
    dest: /nitro/sites/plugins
```
