### ISSUE TITLE
Ability to define environment variables from Nitro config

### ISSUE THREAD

**Issue by brandonkelly** [craftcms/nitro#118]
It should be possible to define custom environment variables from Nitro configs, [similar to Homestead](https://laravel.com/docs/7.x/homestead#environment-variables).

```yaml
env:
  - APP_ENV: "dev"
  - TEST_EMAIL: "test@example.com"
```
