### ISSUE TITLE
Store databases in the config

### ISSUE THREAD

**Issue by brandonkelly** [craftcms/nitro#135]
Machine configs should keep track of databases:

```yaml
databases:
  - engine: mysql
  - version: "5.7"
  - dbs:
    - mydb1
    - mydb2
```

Then the `apply` / `init` commands (and any other commands that apply config changes internally) should start ensuring that each of the configured databases exist.

(`apply` **should not** remove databases that have been removed from the config, though, since that could end up removing databases people created manually within the VM.)
