### ISSUE TITLE
[beta 3 only] Issues with user ubuntu's home directory

### ISSUE THREAD

**Issue by JeanLucEsser** [craftcms/nitro#145]
Maybe it's me doing something wrong, but I have some issues with the just released beta 3 and initializing a new machine:

- user ubuntu's home is not initialized with /etc/skel (no .profile, no .bashrc)
- user ubuntu' home has some weird permissions (owned by root), is this normal behavior?
- home has an empty .composer directory and composer doesn't seem to be installed

Anyone else seeing those?

**Comment by jasonmccallister** [comment]
Hi @JeanLucEsser, that is definitely strange. Can you run `nitro context` and `nitro info` and provide the output here?

It sounds like this is a new machine, but if you came from beta 2, can you run `nitro refresh`? 

I have a feeling that the initialization process failed - and did not complete the rest of the scripts to setup. Can you run provide the log files from these commands?

1. `multipass transfer nitro-dev:/var/log/cloud-init-output.log cloud-init-output.log`
2. `multipass transfer nitro-dev:/var/log/cloud-init.log cloud-init.log`

That should give you a `cloud-init-output.log` and `cloud-init.log`

**Comment by JeanLucEsser** [comment]
Here you go: I destroyed my previous machine and init a new nitro-dev.

`nitro context`
```
Using config: /Users/sierraromeo/.nitro/nitro-dev.yaml
------
php: "7.4"
mounts:
  - source: ~/Sites/vlp
    dest: /home/ubuntu/sites/vlp.test
  - source: ~/Sites/lecontactmoderne
    dest: /home/ubuntu/sites/lecontactmoderne.test
databases:
  - engine: mysql
    version: "5.7"
    port: "3306"
sites:
  - hostname: vlp.test
    webroot: /home/ubuntu/sites/vlp.test/web
  - hostname: lecontactmoderne.test
    webroot: /home/ubuntu/sites/lecontactmoderne.test/web
```

`nitro info`
```
Name:           nitro-dev
State:          Running
IPv4:           192.168.64.2
Release:        Ubuntu 18.04.4 LTS
Image hash:     3b2e3aaaebf2 (Ubuntu 18.04 LTS)
Load:           0.18 0.12 0.09
Disk usage:     2.7G out of 38.6G
Memory usage:   364.5M out of 3.9G
Mounts:         /Users/sierraromeo/Sites/vlp              => /home/ubuntu/sites/vlp.test
                    UID map: 501:default
                    GID map: 20:default
                /Users/sierraromeo/Sites/lecontactmoderne => /home/ubuntu/sites/lecontactmoderne.test
                    UID map: 501:default
                    GID map: 20:default
```

I ran `nitro refresh` just to make sure but no change:
```
Downloading the latest refresh script
Refreshed the templates and configs for the machine to  1.0.0-beta.3
```

Requested logs attached:
[cloud-init-output.log](https://github.com/craftcms/nitro/files/4656824/cloud-init-output.log)
[cloud-init.log](https://github.com/craftcms/nitro/files/4656825/cloud-init.log)
