### ISSUE TITLE
nitro apply exit status 2 on windows

### ISSUE THREAD

**Issue by angrybrad** [craftcms/nitro#158]
Using `develop`, have a machine successfully running with:

```
php: "7.4"
mounts:
- source: D:\dev\nitro
  dest: /home/ubuntu/sites/site.test
sites:
- hostname: site.test
  webroot: /home/ubuntu/sites/site.test/www
```

Change to:

```
php: "7.4"
mounts:
- source: D:\dev\nitro
  dest: /home/ubuntu/sites/site2.test
sites:
- hostname: site2.test
  webroot: /home/ubuntu/sites/site.test/www
```

Run `nitro apply` and get `Error: exit status 2`
