### ISSUE TITLE
Local site contents deleted by nitro

### ISSUE THREAD

**Issue by lukeholder** [craftcms/nitro#162]
Had a nitro machine with this mount config:

```
mounts:
- source: ~/Code/Sites
  dest: /home/ubuntu/sites
```

then edited the `nitro-dev.yaml` to:

```
mounts:
- source: ~/Code/Sites/craft-commerce3
  dest: /home/ubuntu/sites/craft-commerce3.test
- source: ~/Code/Sites/craft-commerce2
  dest: /home/ubuntu/sites/craft-commerce3.test
```
(I can see there is an issue with my config in that both mounts are pointing to the same location)

then ran `nitro apply`

This is the full output: 

https://gist.github.com/lukeholder/16293da4583016aff929d9c28eea5f20

```
➜ nitro apply
Webroot for "craft-commerce3.test" matches
Webroot for "craft-commerce2.test" matches
Webroot for "tenina.test" matches
Removing mount /Users/lh/Code/Sites/craft-commerce3.test from nitro-dev
Removing mount /Users/lh/Code/Sites from nitro-dev
rm: cannot remove '/home/ubuntu/sites/craft-commerce3.test': Is a directory
Error: exit status 1
```

This has deleted the contents of `~/Code/Sites/craft-commerce3.test` on my local machine.

![image](https://user-images.githubusercontent.com/133571/83391825-a7d9c200-a426-11ea-87bd-aa45fbee356e.png)
