### ISSUE TITLE
Let `nitro ssh` open straight into matching mounted directory

### ISSUE THREAD

**Issue by michaelroper** [craftcms/nitro#165]
Is there any way that when running the `nitro ssh` command from a local site folder, it can detect if there is a matching mounted folder, and then drop you straight into that working directory?

Eg, if my mount config looks like this:
```yaml
mounts:
- source: ~/Sites/my-website
  dest: /home/ubuntu/sites/my-website
```
then it would behave like this, noting the paths:
```
michael@local-machine:~/Sites/my-website$ nitro ssh
...
Welcome to Ubuntu 20.04...
ubuntu@nitro-dev:/home/ubuntu/sites/my-website$ 
```
It's a little thing, but would make it a lot easier for connecting from within your project in your IDE, and running things like `composer update` without having to `cd` into directories every time..
