### ISSUE TITLE
Add ability to define cron jobs

### ISSUE THREAD

**Issue by jasonmccallister** [craftcms/nitro#169]
It would be great to have a `cron` option on the config file that would define cron jobs for a virtual machine, something like this:

```yaml
cron:
- command: /home/ubuntu/sites/craft-dev/craft queue/run
  frequency: 5m
  output: /var/logs/nitro/craft-dev-queue.log
```
