### ISSUE TITLE
Add ability to define containers

### ISSUE THREAD

**Issue by jasonmccallister** [craftcms/nitro#170]
It would be great to have support for `containers` in the config file. This would be useful for running container based tools such as [min.io](https://docs.min.io/) (an S3 API compatible storage engine) or other useful tools for local development.

```yaml
containers:
- name: example-minio
  image: minio/minio
  ports:
  - 9000
  environment:
    SOME_KEY: value
  volumes:
  - /path/to/local:/minio/data
  cmd:
  - some
    command
```
