### ISSUE TITLE
After restart craft won't work anymore

### ISSUE THREAD

**Issue by kjvdven** [craftcms/nitro#182]
### Description

After my nitro-dev machine is restarted I can't get craft to run anymore. If I go to my assigned host name, I see the message "this site can't be reached". 

All nitro commands work, I can see the info. I checked if the ip address of the VM had changed, but that was not the case.
No VPN's running, I checked to be sure.

Tried to rename the site to see what would happen and got the following error:
`Error: While parsing config: yaml: line 17: could not find expected ':'`

### Steps to reproduce

1. type in `nitro restart` in console, or reboot computer, or trigger restart machine from multipass 
2. go to the host name you specified during adding the website

### Additional info

- Nitro version: nitro 1.0.0-beta.10
- Multipass version: multipass  1.3.0+mac

**Comment by jasonmccallister** [comment]
@kjvdven can you run `cat ~/.nitro/nitro-dev.yaml` and make sure its valid yaml?

**Comment by kjvdven** [comment]
This is my nitro-dev.yaml

```
php: "7.4"
mounts:
- source: ~/Code/oodit/oodit-craft
  dest: /home/ubuntu/sites/oodit-craft
- source: ~/Code/oodit/oodit-kirby
  dest: /home/ubuntu/sites/oodit-kirby
databases:
- engine: mysql
  version: "5.7"
  port: "3306"
sites:
- hostname: oodit.test
  webroot: /home/ubuntu/sites/oodit-craft/web
- hostname: oodit-kirby.test
  webroot: /home/ubuntu/sites/oodit-kirby/web
y/web
```
