### ISSUE TITLE
Unable to delete a user on Craft Nitro instance because of MySQL read timeout

### ISSUE THREAD

**Issue by ryanpcmcquen** [craftcms/nitro#209]
### Description

I'm attempting to delete a user with 232 entries and the database times out on this. I'm using MySQL and a Nitro instance. Perhaps we can bump the default read timeout to be more than 15 seconds on Nitro?

### Steps to reproduce

1. Have a user with a lot of entries.
2. Delete that user and choose to delete all of their entries.

### Additional info

The failing SQL is:

```
UPDATE `matrixblocks` SET `deletedWithOwner`=1 WHERE `id`='123456'
```

- Nitro version: 1.0.1
- Multipass version: 1.4.0

**Comment by ryanpcmcquen** [comment]
This is the error message:
```
Lost connection to MySQL server during query.Read timeout (15 seconds) reached.
Error code 2013.
```

I don't see anything with a value of 15 though.

**Comment by jasonmccallister** [comment]
@ryanpcmcquen which version of Craft CMS are you running. Do you have any plugins that might be hooking into the user events (that you know of)?

I'm going to try to replicate on my end

**Comment by ryanpcmcquen** [comment]
Craft CMS 3.4.30, the plugins shouldn't matter since even the direct SQL fails. But I don't have any that I know of that would affect user deletion.

**Comment by jasonmccallister** [comment]
@ryanpcmcquen alright, I have my environment setup to replicate. Added 5k entries for a single user and will try. I'm on 3.5.8 but like you said it should not matter (missed that point in your description).

**Comment by ryanpcmcquen** [comment]
@jasonmccallister, any luck?

**Comment by jasonmccallister** [comment]
@ryanpcmcquen I am unable to reproduce this. I am running the following Nitro machine:

```
Using config: /Users/jasonmccallister/.nitro/nitro-dev.yaml
------
php: "7.4"
mounts:
- source: ~/dev/plugins-dev
  dest: /home/ubuntu/sites/plugins-dev
databases:
- engine: mysql
  version: "5.7"
  port: "3306"
sites:
- hostname: plugins.nitro
  webroot: /home/ubuntu/sites/plugins-dev/web
```

I added 5000 entries and deleted a user and transferred to another user and it happened quickly. I was on the latest Craft (3.5.11.1). I'm going to downgrade to 3.4.30. I don't know of any issues related to removing users and updates.

Can you try `nitro db restart` to restart the database container and see if that resolves it?
