### ISSUE TITLE
Add support for project-level config files

### ISSUE THREAD

**Issue by jamesmacwhite** [craftcms/nitro#259]
### Description

You are going to get tired of my name appearing here I'm sure!

Nitro 2 is nice and straight forward to provision environments with `nitro init` and `nitro add` but requires user interaction on various steps, due to the various choices and options. Choice is of course, great, but I was wondering if it has been considered letting Nitro essentially be guided non interactively perhaps with a project specific yml file that acts as an answer file.

The idea being, you can have all the Nitro options for a specific Craft site stored in some form of answer file that Nitro can then go through without having to ask for user input. i.e. define the specific PHP version, does xdebug need to be enabled, any custom PHP ini options, the database name etc.

These days I'm a fan of being able to script anything and was wondering if it's been considered for Nitro in this regard? The use case would be multiple developer projects who all need the same environment. I'm sure the Nitro 2 docs will be great. clear and straight forward when it's out of Beta, it's more about the environment parameters like database engine, PHP Version and others for me and being able to have these consistently provisioned in multi dev scenarios or indeed if you have multiple OS environments for a single project.

Thanks!

**Comment by jamesmacwhite** [comment]
I guess an alternative would perhaps to store a copy of `~/.nitro/nitro.yml` specifically for the project in the source tree, with all the configuration written out, so `nitro init` and `nitro apply` can be used, without having to go through the configuration stages.

**Comment by jasonmccallister** [comment]
@jamesmacwhite we have had a discussion internally about this and think we have a good solution. We are going to sort out some details and discuss some specifics but we are most likely going to move to support storing a `nitro.yaml` in the project directory that can be versioned with the project to allow teams to share configs easily.

**Comment by jamesmacwhite** [comment]
@jasonmccallister Thanks for this. I think that's the solution. For me it's basically have a single source for provisioning the environment, that's where Docker and the `docker-compose.yml` and `Dockerfile` are great to 
guarantee the same environment each time. If Nitro can be similar, that would be ideal!

**Comment by jasonmccallister** [comment]
@jamesmacwhite yeah that makes sense, we are imagining it would work exactly the same way. 

The initial concept is to keep the `sites` on the main `nitro.yaml` and add an existing `paths` that contains all of the project site specific details... 

The main config file would look something like this:

```yaml
blackfire:
    server_id: '****************'
    server_token: '********************************'
databases:
    - engine: mysql
      version: "8.0"
      port: "3306"
    - engine: postgres
      version: "13"
      port: "5432"
    - engine: mariadb
      version: "10.5"
      port: "3307"
paths:
   - ~/dev/plugins-dev/nitro.yaml
sites:
    - hostname: plugins-dev.nitro
      path: ~/dev/plugins-dev
      version: "8.0"
      webroot: web
      xdebug: true
      blackfire: false
    - hostname: tutorial.nitro
      path: ~/dev/tutorial
      version: "7.4"
      webroot: web
      xdebug: false
      blackfire: false
```

The sites defined in `path` would take precedence over anything defined in `sites`. The project would then store a `nitro.yaml` file that contained only the project specific setups and allow teams to share environments (e.g. hostnames and aliases) using version control:

```yaml
hostname: tutorial.nitro
version: "7.4"
webroot: web
xdebug: false
blackfire: false
```

When running `apply` the `path` sites would not prompt for settings and just use the config file.

Additionally, we are considering a `nitro scan` command to search a directory (e.g. `~/dev/`) for any `nitro.yaml` configs and ask a user to "add it". There are times where you may not be actively working on a project, so the ability to search and quickly add might be useful.

Very much a wip, but it makes a lot of sense to make this have better support for teams.
