### ISSUE TITLE
[2.0.0-beta.7] Caddy HTTP 502 error on specific site

### ISSUE THREAD

**Issue by jamesmacwhite** [craftcms/nitro#262]
### Description

I've configured a few Craft sites as per my config here, real names and paths changed, but just for general purposes.

```
sites:
- blackfire: false
  hostname: project1.nitro
  path: ~/Projects/project1
  php: {}
  version: "7.4"
  webroot: web
  xdebug: false
- blackfire: false
  hostname: project2.nitro
  path: ~/Projects/project2
  php: {}
  version: "7.3"
  webroot: public
  xdebug: false
- blackfire: false
  hostname: project3.nitro
  path: ~/Projects/project3
  php: {}
  version: "7.3"
  webroot: public
  xdebug: false
```

* Project 1: Craft 3 site
* Project 2: Craft 2 site
* Project 3: Craft 2 site.

Project 1 and 2 work fine, project 3 throws a 502 error when being accessed.

```
{"level":"error","ts":1614613690.1539984,"logger":"http.log.error","msg":"dial tcp 172.18.0.2:8080: connect: connection refused","request":{"remote_addr":"172.18.0.1:37656","proto":"HTTP/2.0","method":"GET","host":"project3.nitro","uri":"/","headers":{"Sec-Fetch-Site":["none"],"Sec-Fetch-Mode":["navigate"],"Sec-Fetch-User":["?1"],"Accept-Encoding":["gzip, deflate, br"],"Cache-Control":["max-age=0"],"Upgrade-Insecure-Requests":["1"],"User-Agent":["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36"],"Accept":["text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9"],"Sec-Fetch-Dest":["document"],"Accept-Language":["en-GB,en-US;q=0.9,en;q=0.8"]},"tls":{"resumed":false,"version":772,"cipher_suite":4865,"proto":"h2","proto_mutual":true,"server_name":"project3.nitro"}},"duration":0.0006096,"status":502,"err_id":"i4ju8ajw7","err_trace":"reverseproxy.statusError (reverseproxy.go:783)"}
```

This is coming from the Caddy proxy container, the site is not able to get to the nginx container due to the connection refused error. I tried switching the PHP version to 7.2 in case there was a conflict with the same PHP version, but this didn't seem to help.

Any pointers on being able to debug the connection refused error?
