### ISSUE TITLE
PHP not using ENV ini values?

### ISSUE THREAD

**Issue by michaelroper** [craftcms/nitro#268]
### Description

So today I hit the stupid `max_input_vars` error when saving a matrix field. Now, the error message mentioned I'd hit the limit of _2000_, but I know that the default nitro setting is 5000, but if I look on the `/admin/utilities/php-info` page, I see this:

> **Core**
> `max_input_vars = 2000`
> 
> **Environment**
> `PHP_MAX_INPUT_VARS = 5000`
> 
> **PHP Variables**
> `$_SERVER['PHP_MAX_INPUT_VARS'] = 5000`
> `$_ENV['PHP_MAX_INPUT_VARS'] = 5000`

Why might it be using the `2000` value, and not the `5000`?

I tried the same with the `memory_limit` value, by using `nitro iniset` to set it to 768M and found the same issue.

> **Core**
> `memory_limit = 512M`
> 
> **Environment**
> `PHP_MEMORY_LIMIT = 768M`
> 
> **PHP Variables**
> `$_SERVER['PHP_MEMORY_LIMIT'] = 768M`
> `$_ENV['PHP_MEMORY_LIMIT'] = 768M`

All values seem correct in `nitro.yaml`, and i have made sure everything is up to date by `brew upgrade nitro` and `nitro update`, and stopped docker, trashed all the containers and images, restarted docker, then did `nitro apply` to pull fresh images and rebuild the containers - still no change.

### Additional info

```
Nitro CLI:       2.0.2
Nitro gRPC:      2.0.2
Docker API:      1.41 (1.12 min)
Docker CLI:      1.41
--
PHP:             7.4.15 (and 8.0)
Postgres:        13
Craft:           3.6.7
```

**Comment by jasonmccallister** [comment]
@michaelroper does your nitro.yaml have the memory provided on your site? Under sites.site.php.setting?

**Comment by michaelroper** [comment]
@jasonmccallister it has the 768M value that was put there by `nitro iniset`
```yaml
sites:
    - hostname: voc-www-cms.test
      path: ~/Sites/voc-www-cms
      version: "7.4"
      php:
        displayerrors: false
        maxexecutiontime: 0
        maxinputvars: 6000
        maxinputtime: 0
        maxfileupload: ""
        memorylimit: 768M
        opcacheenable: false
        opcacherevalidatefreq: 0
        postmaxsize: ""
        uploadmaxfilesize: ""
      webroot: web
      xdebug: false
      blackfire: false
```
