### ISSUE TITLE
Be able to use shared SSH keys

### ISSUE THREAD

**Issue by danieladarve** [craftcms/nitro#297]
### Description
I have a project that has a private repository, when I run composer install, it fails.
Using a docker-compose.yml i usually can add my shared keys like so
```
services:
  container:
    image: image-name
    secrets:
      - user_ssh_key
secrets:
  user_ssh_key:
    file: ~/.ssh/my_private_key
```
It would awesome if nitro could implement something similar in the nitro yml like:
```
secrets:
  user_ssh_key:
    file: ~/.ssh/my_private_key
sites:
    - hostname: craft-crm.nitro
      path: ~/Development/craft/craft-crm
      version: "8.0"
      webroot: web
      xdebug: false
      blackfire: false
      secrets:
        - user_ssh_key
```
