### ISSUE TITLE
[FR] Prompt to set the `path`

### ISSUE THREAD

**Issue by lindseydiloreto** [craftcms/nitro#300]
Here is a Nitro config from a [loosely related thread](https://github.com/craftcms/nitro/issues/294#issuecomment-801637989)...

```yaml
- hostname: project.test
  path: ~/Sites/projects
  version: "7.4"
  webroot: path/to/site/public
  xdebug: false
  blackfire: false
```

When adding a new Nitro site, you will see the following prompt:

```
Enter the webroot for the site [public]:
```

**Can we get a similar prompt for the `path`?**

```
Enter the path for the site [~/path/to/current-folder]:
```

Those two values obviously go hand-in-hand. Looking at the config example above, it's clear that specifying a `webroot` of `public` barely gets halfway there. It's not safe to assume that our _current_ directory should be the `path`.

My ideal setup would have looked something like this...

```
Enter the path for the site [~/Sites/projects/path/to/site]:  ~/Sites/projects

Enter the webroot for the site [public]:  path/to/site/public  <--- Moved "path/to/site"
```

Would it be possible to add another prompt to manage the `path` value?
