### ISSUE TITLE
No database engine options when adding a site

### ISSUE THREAD

**Issue by peteheaney** [craftcms/nitro#304]
### Description

When adding a site, when it asks "Select the database engine", there are no options listed.  I can't get past this point.

<img width="358" alt="Screenshot 2021-03-18 at 15 27 30" src="https://user-images.githubusercontent.com/29060670/111652045-a71bec00-87fe-11eb-8303-79c349191d0e.png">

Possibly relevant: during installation of Nitro, I answered Yes to "Would you like to use MySQL" but No to "Would you like to use PostgreSQL".

Also possibly relevant: during installation, I got this error:

```
creating proxy Error: unable to start the nitro container, Error response from daemon: Ports are not available: port is already allocated.
```

### Steps to reproduce

1. Install Nitro with MySQL but not PostgreSQL
2. Add a site: `nitro add`

### Additional info

- Nitro version: `nitro version` returns `Error: unable to get version from the gRPC API`
- Docker version: 3.2.2

**Comment by jasonmccallister** [comment]
@peteheaney can you provide your `nitro context --yaml` output?

**Comment by peteheaney** [comment]
```
databases:
    - engine: mysql
      version: "5.7"
      port: "3306"
services:
    dynamodb: false
    mailhog: false
    minio: false
    redis: true
sites:
    - hostname: example.nitro
      path: ~/www/example
      version: "7.4"
      webroot: web
      xdebug: false
      blackfire: false
```

Thanks
