### ISSUE TITLE
[FR] Automatically redirect to `https`

### ISSUE THREAD

**Issue by lindseydiloreto** [craftcms/nitro#327]
I absolutely _love_ the fact that Nitro includes `https` compatibility "out of the box"! ❤️ 

Is there any way to have each site **automatically redirect** to the `https` version of the site? Or perhaps have a config setting with a value of `yes`/`true` to redirect by default?

**Comment by jamesmacwhite** [comment]
I'm going to present a scenario where this might need some caution. If you use something like browsersync or front end loader that proxies the site, forcing HTTPS means this will likely fail without the certificates in the path with manual configuration. Allowing plain HTTP without forcing means you can still proxy HTTP without issues.

If forcing HTTPS it should be a configurable option in my opinion.

**Comment by jasonmccallister** [comment]
I think an option makes the most sense, however it would be nice to have it per site. 

What is there was a new configuration option that looked something like this:

```yaml
sites:
    - hostname: tutorial.nitro
      path: ~/Sites/tutorial.nitro
      force_https: true
      version: "8.0"
      webroot: web
      xdebug: false
      blackfire: false
```

That way it is specific to each site but should default to `false` to avoid potential issues for people trying to run node/npm in the container like @jamesmacwhite pointed out above.
