### ISSUE TITLE
`nitro extensions` wonky behavior

### ISSUE THREAD

**Issue by angrybrad** [craftcms/nitro#339]
### Description

After some random sampling, it seems that _none_ of the extensions the command accepts get enabled for php-fpm and _some_ of the extensions get enabled for the cli.

For example, nitro.yaml

```
sites:
    - hostname: craft3.support.test
      path: ~/dev/support/craft3.support.test
      version: "7.4"
      extensions:
        - pcntl
        - xsl
```

Utilities->PHP Info from the Craft control panel doesn't list either (other than unrelated author credits).

If you `nitro ssh` into the site, you get nothing for `xsl`:

```
~/dev/support/craft3.support.test 3m 9s
❯ nitro ssh
connecting to craft3.support.test
/app $ php -i | grep "xsl"
/app $
```

But you do get results for `pcntl`:

```
/app $ php -i | grep "pcntl"
/usr/local/etc/php/conf.d/docker-php-ext-pcntl.ini,
pcntl
pcntl support => enabled
```

And if you remove all of the extensions from nitro.yaml, run `nitro apply`, then `nitro ssh`, `pcntl` is now missing from the CLI (as expected):

```
❯ nitro ssh
connecting to craft3.support.test
/app $ php -i | grep "pcntl"
/app $
```

### Additional info

- Nitro version: 2.0.7
- Docker version: 3.3.1
