### ISSUE TITLE
Support custom Dockerfile for site containers

### ISSUE THREAD

**Issue by jasonmccallister** [craftcms/nitro#344]
### Description

While the images used for Nitro sites provide most of what users need, there are times when a custom Dockerfile is useful to better mimic a production environment locally but still get all the benefits from Nitro such as the automatic HTTPS and database features. Nitro should have an advanced use case to handle user provided Dockerfiles. 

There should be two main changes to support this feature:

1. The sites config should be updated to indicate the site uses a custom container
2. All sites should expose port 8080 (or define on the port on the site?)
3. The `apply` command should support building the container from the Dockerfile if present

What we don't want is to have `apply` build a container every single time, although builds would only be lengthy the first time, instead we could md5 the Dockerfile contents and add it as a label to the custom container and that can be the key to tell if its different and should rebuild.

The proposed site config could look something like this:

```
sites:
    - hostname: blog.nitro
      path: ~/Sites/blog.nitro
      version: "8.0"
      webroot: web
      xdebug: false
      blackfire: false
      custom: my.Dockerfile # would live at ~/Sites/blog.nitro/my.Dockerfile
      port: 8001 #would default to 8080 if not defined 
``` 
Sites that do not use a custom Dockerfile will not contain the last two keys of the config.. 

Some things to consider:

1. Supporting `npm`, `composer`, `craft`, and related commands with custom containers
2. Displaying output for the build in `apply`?

Adding support for this feature also means "any" application can run with Nitro (e.g. node, pyhton, etc).
