### ISSUE TITLE
Nitro extremely slow on macOS Big Sur

### ISSUE THREAD

**Issue by jan-thoma** [craftcms/nitro#409]
### Description

On macOS Big Sur the nitro containers are extemly slow. For example:

- Uncached Graphql Queries can take up to 20s in comparsion to a shared hosting where the same query take less than > 1s
- CP Call are slower than excpected
- Installing updates and plugins sometimes ends in a timeout

We use a external database container (MySQL) on a docker server on the same network, the connection from the dev machines are 1GB/s or even 10GB/s. 

Running Craft instances based on the provided docker images with the same project and and the external database or internal server yields good performance.

Are the nitro containers somehow restricted in ressource usage or are there any limits which can be leveraged?

### Steps to reproduce

1. Spin up nitro container
2. Watch it beeing slow

### Additional info

- Nitro version: 2.0.8
- Docker version: 20.10.8, build 3967b7d
- OS: macOS Big Sur 11.5.2 (20G95)

**Comment by timkelty** [comment]
> Running Craft instances based on the provided docker images with the same project and and the external database or internal server yields good performance.

@jan-thoma are you able to share details about this setup where you're seeing good performance? (e.g. is it docker-compose based, something else?)

Also if you're able to send over something reproducible (project config files, composer.json/lock, nitro config) that would help me do a better test.

**Comment by jan-thoma** [comment]
@timkelty

Here's an docker-compose file we use in production. We use traefik as reverse proxy for our containers. The Fronted is a Vite-SSR container which shouldn't matter much. 

We use this setup primarily on a 16C/32T Machine with 64GB RAM and standard SATA-SSD, which runs fast as hell. Even on a Macbook Pro 2016 with 4C/8T and 16GB Ram it runs magnitudes faster than the nitro containers.

```
version: '3.2'
services:
    node:
        image: registry.io.t-k-f.ch/tkf/tkf-next-3-frontend:stable
        restart: always
        networks:
            - external
        depends_on:
            - craft
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=${TRAEFIK_NETWORK}"

            - "traefik.http.routers.${TRAEFIK_NAME_FRONTEND}.rule=Host(${TRAEFIK_HOST_FRONTEND})"
            - "traefik.http.routers.${TRAEFIK_NAME_FRONTEND}.entrypoints=websecure"
            - "traefik.http.routers.${TRAEFIK_NAME_FRONTEND}.tls.certresolver=letsencrypt-tls"
            - "traefik.http.routers.${TRAEFIK_NAME_FRONTEND}.middlewares=${TRAEFIK_NAME_FRONTEND}-www-to-non-www"

            - "traefik.http.middlewares.${TRAEFIK_NAME_FRONTEND}-www-to-non-www.redirectregex.regex=^https://www.(.*)"
            - "traefik.http.middlewares.${TRAEFIK_NAME_FRONTEND}-www-to-non-www.redirectregex.replacement=https://$${1}"
            - "traefik.http.middlewares.${TRAEFIK_NAME_FRONTEND}-www-to-non-www.redirectregex.permanent=true"

            - "traefik.http.services.${TRAEFIK_NAME_FRONTEND}.loadbalancer.server.port=${TRAEFIK_PORT_FRONTEND}"
        environment:
            - VITE_APP_TITLE=${VITE_APP_TITLE}
            - VITE_APP_GRAPHQL_API=${VITE_APP_GRAPHQL_API}
            - VITE_APP_CACHE_PAGES=${VITE_APP_CACHE_PAGES}
            - VITE_APP_CACHE_AGE=${VITE_APP_CACHE_AGE}
    craft:
        image: registry.io.t-k-f.ch/tkf/tkf-next-3-backend:stable
        restart: always
        networks:
            - external
            - internal
        volumes:
            - backend:/app/web/data
        depends_on:
            - mysql
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=${TRAEFIK_NETWORK}"

            - "traefik.http.routers.${TRAEFIK_NAME_BACKEND}.rule=Host(${TRAEFIK_HOST_BACKEND})"
            - "traefik.http.routers.${TRAEFIK_NAME_BACKEND}.entrypoints=websecure"
            - "traefik.http.routers.${TRAEFIK_NAME_BACKEND}.tls.certresolver=letsencrypt-tls"
            - "traefik.http.routers.${TRAEFIK_NAME_BACKEND}.middlewares=${TRAEFIK_NAME_BACKEND}-www-to-non-www"

            - "traefik.http.middlewares.${TRAEFIK_NAME_BACKEND}-www-to-non-www.redirectregex.regex=^https://www.(.*)"
            - "traefik.http.middlewares.${TRAEFIK_NAME_BACKEND}-www-to-non-www.redirectregex.replacement=https://$${1}"
            - "traefik.http.middlewares.${TRAEFIK_NAME_BACKEND}-www-to-non-www.redirectregex.permanent=true"

            - "traefik.http.services.${TRAEFIK_NAME_BACKEND}.loadbalancer.server.port=${TRAEFIK_PORT_BACKEND}"
        environment:
            - DB_DRIVER=${DB_DRIVER}
            - DB_SERVER=${DB_SERVER}
            - DB_PORT=${DB_PORT}
            - DB_DATABASE=${DB_DATABASE}
            - DB_USER=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}
            - DB_SCHEMA=${DB_SCHEMA}
            - DB_TABLE_PREFIX=${DB_TABLE_PREFIX}
            - APP_ID=${CRAFT_APP_ID}
            - ENVIRONMENT=${CRAFT_ENVIRONMENT}
            - SECURITY_KEY=${CRAFT_SECURITY_KEY}
            - TIMEZONE=${CRAFT_TIMEZONE}
            - WEB=${CRAFT_WEB}
    mysql:
        image: mysql
        restart: always
        networks:
            - internal
        volumes:
            - database:/var/lib/mysql
        environment:
            - MYSQL_RANDOM_ROOT_PASSWORD=${DB_PASSWORD}
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USER}
            - MYSQL_PASSWORD=${DB_PASSWORD}
networks:
    external:
        external: true
    internal:
        driver: bridge
volumes:
    database:
    backend:

```

Here's the corresponding composer.json

```
{
  "require": {
    "craftcms/cms": "3.7.10",
    "vlucas/phpdotenv": "^3.4.0"
  },
  "require-dev": {
    "yiisoft/yii2-shell": "^2.0.3"
  },
  "autoload": {
    "psr-4": {
      "modules\\": "modules/"
    }
  },
  "config": {
    "sort-packages": true,
    "optimize-autoloader": true,
    "platform": {
      "php": "7.2.5"
    }
  },
  "scripts": {
    "post-root-package-install": [
      "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
    ]
  }
}

```

The Docker file which build the craft container

```
FROM composer:2 as vendor
COPY composer.json composer.json
COPY composer.lock composer.lock
RUN composer install --ignore-platform-reqs --no-interaction --prefer-dist

FROM craftcms/nginx:7.4

WORKDIR /app

COPY --chown=www-data:www-data --from=vendor /app/vendor/ /app/vendor/
COPY --chown=www-data:www-data . .

RUN chmod +x bootstrap.sh
RUN mkdir storage

ENTRYPOINT ["./bootstrap.sh"]
```

And the bootstrap file to apply pending changes

```
#!/bin/sh

./craft migrate/all
./craft project-config/apply
./craft clear-caches/cp-resources

/usr/bin/supervisord -c /etc/supervisor/conf.d/supervisor.conf
```
