### ISSUE TITLE
Minio service no longer works

### ISSUE THREAD

**Issue by jasonmccallister** [craftcms/nitro#445]
### Description
The Minio image has a major breaking change and has split the API port and console port. They no longer allow running both the API and console port on the same address (e.g. 9000).

We need to update the `nitro enable minio` command to support this new change.

There is a work around for now by creating a `docker-compose.yaml` file and joining the `nitro-network`.

1. Add a `docker-compose.yaml` with the following content in any location
2. Run `docker-compose up -d`
3. Follow the documentation on https://craftcms.com/docs/nitro/2.x/services/minio.html
4. Use the username and password `minioadmin`.

```yaml
version: "3.7"
services:
  minio.service.nitro:
    image: minio/minio:latest
    ports:
      - 9001:9001
    networks:
      - nitro-network
    command:
      - server
      - /data
      - --console-address=:9001
networks:
  nitro-network:
    external: true
```

### Steps to reproduce

1. `nitro enable minio` - using the latest tag
2. Visit https://minio.service.nitro and :(

### Additional info

- Nitro version: v2 and v3
