### ISSUE TITLE
Add a way to specify default databases

### ISSUE THREAD

**Issue by angrybrad** [craftcms/nitro#80]
Might look something like this in nitro.yaml

```
databases:
- engine: mysql
  version: "5.7"
  port: "3306"
  names:
  - db1
    db2
```

Along with a console command to facilitate
