### ISSUE TITLE
More verbose output for `apply`

### ISSUE THREAD

**Issue by brandonkelly** [craftcms/nitro#95]
The `apply` command should output info about everything it’s doing, based on the changes it finds. At least in the case of adding new mounts, there is no mention of it.

#### Steps to reproduce

1. Add a new mount to the config:

    ```yaml
    mounts:
      - source: /Users/brandon/Sites
        dest: /nitro/test
    ```

2. Run `apply`.

    ```
    $ nitro apply
    Applied changes from /Users/brandon/.nitro/nitro-dev.yaml                       
    Editing your hosts file
    Password:
    There are no sites in the config file to remove
    ```
