### ISSUE TITLE
apply not removing mounts

### ISSUE THREAD

**Issue by brandonkelly** [craftcms/nitro#96]
If you have a custom mount and then remove it by removing the whole `mounts` array in the config, running `nitro apply` will not delete the mount. I even tried running `nitro restart`, but that didn’t help either.

#### Steps to reproduce

1. Add a new mount to the config:

    ```yaml
    mounts:
      - source: /Users/brandon/Sites
        dest: /nitro/test
    ```

2. Run `nitro apply`

3. Verify that the new mount was added successfully.

    ```
    $ nitro ssh
    ubuntu@nitro-dev:~$ cd /nitro
    ubuntu@nitro-dev:/nitro$ ls
    sites  test
    ubuntu@nitro-dev:/nitro$ exit
    ```

4. Delete the mount from the config

5. Run `nitro apply`

#### Expected behavior

The mount should be removed, as it’s no longer listed in the config.

#### Actual behavior

The mount remains, even after restarting the machine.

**Comment by jasonmccallister** [comment]
@brandonkelly can you try this in on the latest release? I just ran through a few scenarios locally and can't reproduce.

**Comment by jasonmccallister** [comment]
I'm pretty sure this was resolved when we tagged a beta release. I performed the following steps on my local using 1.0.0-beta.2:

1. Created machine called issue96 (`nitro -m issue96 init`)
2. Manually added a mount using `nitro -m issue96 edit`
3. Ran `nitro -m issue96 apply` 
4. Verified the mount exists using `nitro -m issue96 info`
5. Manually removed the mount using `nitro -m issue96 edit`
6. Run `nitro -m issue96 apply`
7. Verified the mount was removed from the config using `nitro -m issue96 context` and the machine using `nitro -m issue96 info` 

Here is the output of `nitro -m issue96 context` for step 3:

```yaml
php: "7.4"
mounts:
  - source: /Users/jasonmccallister/dev
    dest: /nitro/test
databases:
  - engine: mysql
    version: "5.7"
    port: "3306"
```

@brandonkelly can you verify this on the latest beta release?
